[build]
  command = "npm run build:netlify"
  publish = "dist/gis-ingenieria-web/browser"

[build.environment]
  NODE_VERSION = "20"

# Redirect all routes to index.html for Angular client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle specific routes
[[redirects]]
  from = "/home"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/services"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff" 