[build]
  command = "npm run build:netlify"
  publish = "dist/gis-ingenieria-web/browser"

[build.environment]
  NODE_VERSION = "18"

# Disable framework detection
[build.processing]
  skip_processing = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff" 